<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
      <PackageReference Include="Azure.Identity" Version="1.19.0" />
      <PackageReference Include="dotenv.net" Version="4.0.1" />
      <PackageReference Include="Microsoft.Agents.AI" Version="1.0.0-rc4" />
      <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc4" />
    </ItemGroup>

    <ItemGroup>
      <None Update=".env">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="skills\employee-onboarding\assets\onboarding-checklist.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="skills\employee-onboarding\SKILL.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="skills\employee-onboarding\references\ONBOARDING_FAQ.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="skills\expense-report\assets\expense-report-template.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="skills\expense-report\references\POLICY_FAQ.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="skills\expense-report\SKILL.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
